name: CI

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-unix:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macOS-latest, ubuntu-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Makefile
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'debian-latest'
        run: |
          apt update
          apt install -y build-essential

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.3

      - name: Build
        # if: runner.os != 'Windows'
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Test
        run: |
          cd build
          ./_build/binaries/io ../libs/iovm/tests/correctness/run.io

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
